# Generated by Django 3.1.3 on 2020-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image_des', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=1000)),
                ('image_imgur_suffix', models.CharField(max_length=15, null=True)),
                ('image_thumbnail', models.URLField(max_length=1000, null=True)),
                ('image_dimenX', models.IntegerField()),
                ('image_dimenY', models.IntegerField()),
            ],
        ),
    ]
