# Generated by Django 4.0.4 on 2022-06-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0004_alter_category_id_alter_comments_id_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
