# Generated by Django 4.0.4 on 2022-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0006_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Public')], default=1),
        ),
    ]
