# Generated by Django 4.0.4 on 2022-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0007_alter_comments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
