# Generated by Django 4.1.2 on 2022-10-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0008_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
